#pragma once
#include <stdint.h>
// NTC table generated by https://www.sebulli.com/ntc/index.php
// NTC values are 10k pull-up resistor 10K Beta value 3950

int16_t NTC_ADC2Temperature(uint16_t adc_value);

